from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWebEngineWidgets import QWebEngineView as QWebView
from pyqtgraph import PlotWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setFixedSize(1098, 852)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1101, 861))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 781, 481))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.comboBox_density = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_density.setEnabled(False)
        self.comboBox_density.setGeometry(QtCore.QRect(10, 70, 351, 41))
        self.comboBox_density.setObjectName("comboBox_density")
        self.comboBox_density.addItem("")
        self.comboBox_density.setItemText(0, "")
        self.comboBox_density.addItem("")
        self.comboBox_density.addItem("")
        self.comboBox_density.addItem("")
        self.comboBox_density.addItem("")
        self.comboBox_density.addItem("")
        self.comboBox_density.addItem("")
        self.comboBox_density.addItem("")
        self.comboBox_density.addItem("")
        self.comboBox_density.addItem("")
        self.comboBox_density.addItem("")
        self.comboBox_density.addItem("")
        self.comboBox_density.addItem("")
        self.comboBox_density.addItem("")
        self.comboBox_density.addItem("")
        self.comboBox_density.addItem("")
        self.density_label = QtWidgets.QLabel(self.groupBox)
        self.density_label.setGeometry(QtCore.QRect(10, 40, 251, 31))
        self.density_label.setObjectName("density_label")
        self.speed_label = QtWidgets.QLabel(self.groupBox)
        self.speed_label.setGeometry(QtCore.QRect(10, 120, 191, 31))
        self.speed_label.setObjectName("speed_label")
        self.mass_label = QtWidgets.QLabel(self.groupBox)
        self.mass_label.setGeometry(QtCore.QRect(420, 120, 271, 31))
        self.mass_label.setObjectName("mass_label")
        self.startspeedbox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.startspeedbox.setGeometry(QtCore.QRect(10, 150, 351, 41))
        self.startspeedbox.setMaximum(10000.99)
        self.startspeedbox.setObjectName("startspeedbox")
        self.massBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.massBox.setEnabled(False)
        self.massBox.setGeometry(QtCore.QRect(420, 150, 351, 41))
        self.massBox.setMaximum(10000.99)
        self.massBox.setObjectName("massBox")
        self.speedframe = QtWidgets.QFrame(self.groupBox)
        self.speedframe.setGeometry(QtCore.QRect(10, 200, 351, 111))
        self.speedframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.speedframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.speedframe.setObjectName("speedframe")
        self.metresps = QtWidgets.QRadioButton(self.speedframe)
        self.metresps.setGeometry(QtCore.QRect(20, 20, 171, 26))
        self.metresps.setObjectName("metresps")
        self.kilometresph = QtWidgets.QRadioButton(self.speedframe)
        self.kilometresph.setGeometry(QtCore.QRect(20, 60, 161, 26))
        self.kilometresph.setObjectName("kilometresph")
        self.milesph = QtWidgets.QRadioButton(self.speedframe)
        self.milesph.setGeometry(QtCore.QRect(200, 20, 141, 26))
        self.milesph.setObjectName("milesph")
        self.yardsps = QtWidgets.QRadioButton(self.speedframe)
        self.yardsps.setGeometry(QtCore.QRect(200, 60, 141, 26))
        self.yardsps.setObjectName("yardsps")
        self.massframe = QtWidgets.QFrame(self.groupBox)
        self.massframe.setEnabled(False)
        self.massframe.setGeometry(QtCore.QRect(420, 200, 351, 111))
        self.massframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.massframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.massframe.setObjectName("massframe")
        self.kilograms = QtWidgets.QRadioButton(self.massframe)
        self.kilograms.setGeometry(QtCore.QRect(20, 20, 171, 26))
        self.kilograms.setObjectName("kilograms")
        self.pounds = QtWidgets.QRadioButton(self.massframe)
        self.pounds.setGeometry(QtCore.QRect(20, 60, 161, 26))
        self.pounds.setObjectName("pounds")
        self.grams = QtWidgets.QRadioButton(self.massframe)
        self.grams.setGeometry(QtCore.QRect(200, 20, 141, 26))
        self.grams.setObjectName("grams")
        self.tons = QtWidgets.QRadioButton(self.massframe)
        self.tons.setGeometry(QtCore.QRect(200, 60, 141, 26))
        self.tons.setObjectName("tons")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(420, 40, 351, 31))
        self.label.setObjectName("label")
        self.start_height = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.start_height.setGeometry(QtCore.QRect(420, 70, 351, 41))
        self.start_height.setMaximum(99000.99)
        self.start_height.setObjectName("start_height")
        self.angle_label = QtWidgets.QLabel(self.groupBox)
        self.angle_label.setGeometry(QtCore.QRect(10, 320, 621, 31))
        self.angle_label.setObjectName("angle_label")
        self.anglebox = QtWidgets.QSpinBox(self.groupBox)
        self.anglebox.setGeometry(QtCore.QRect(10, 350, 761, 41))
        self.anglebox.setMaximum(90000)
        self.anglebox.setObjectName("anglebox")
        self.angleframe = QtWidgets.QFrame(self.groupBox)
        self.angleframe.setGeometry(QtCore.QRect(10, 400, 761, 41))
        self.angleframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.angleframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.angleframe.setObjectName("angleframe")
        self.degrees = QtWidgets.QRadioButton(self.angleframe)
        self.degrees.setGeometry(QtCore.QRect(30, 0, 101, 41))
        self.degrees.setObjectName("degrees")
        self.radians = QtWidgets.QRadioButton(self.angleframe)
        self.radians.setGeometry(QtCore.QRect(230, 0, 101, 41))
        self.radians.setObjectName("radians")
        self.minutes = QtWidgets.QRadioButton(self.angleframe)
        self.minutes.setGeometry(QtCore.QRect(430, 0, 101, 41))
        self.minutes.setObjectName("minutes")
        self.seconds = QtWidgets.QRadioButton(self.angleframe)
        self.seconds.setGeometry(QtCore.QRect(630, 0, 101, 41))
        self.seconds.setObjectName("seconds")
        self.systemcharacteristics = QtWidgets.QGroupBox(self.tab)
        self.systemcharacteristics.setGeometry(QtCore.QRect(790, 0, 301, 481))
        self.systemcharacteristics.setAlignment(QtCore.Qt.AlignCenter)
        self.systemcharacteristics.setObjectName("systemcharacteristics")
        self.time_char = QtWidgets.QDoubleSpinBox(self.systemcharacteristics)
        self.time_char.setGeometry(QtCore.QRect(10, 440, 280, 31))
        self.time_char.setObjectName("time_char")
        self.time_char.setRange(0.0001, 100)
        self.time_char.setDecimals(4)
        self.time_label = QtWidgets.QLabel(self.systemcharacteristics)
        self.time_label.setGeometry(QtCore.QRect(10, 410, 280, 31))
        self.time_label.setObjectName("time_label")
        self.time_label.setText("Время за шаг вычислений в секундах")
        self.planet_label = QtWidgets.QLabel(self.systemcharacteristics)
        self.planet_label.setGeometry(QtCore.QRect(10, 40, 141, 31))
        self.planet_label.setObjectName("planet_label")
        self.comboBox_planet = QtWidgets.QComboBox(self.systemcharacteristics)
        self.comboBox_planet.setGeometry(QtCore.QRect(10, 70, 281, 41))
        self.comboBox_planet.setObjectName("comboBox_planet")
        self.comboBox_planet.addItem("")
        self.comboBox_planet.setItemText(0, "")
        self.comboBox_planet.addItem("")
        self.comboBox_planet.addItem("")
        self.comboBox_planet.addItem("")
        self.comboBox_planet.addItem("")
        self.comboBox_planet.addItem("")
        self.comboBox_planet.addItem("")
        self.comboBox_planet.addItem("")
        self.comboBox_planet.addItem("")
        self.comboBox_planet.addItem("")
        self.comboBox_planet.addItem("")
        self.comboBox_planet.addItem("")
        self.environment_label = QtWidgets.QLabel(self.systemcharacteristics)
        self.environment_label.setGeometry(QtCore.QRect(10, 130, 131, 31))
        self.environment_label.setScaledContents(False)
        self.environment_label.setWordWrap(False)
        self.environment_label.setObjectName("environment_label")
        self.comboBox_environment = QtWidgets.QComboBox(self.systemcharacteristics)
        self.comboBox_environment.setEnabled(False)
        self.comboBox_environment.setGeometry(QtCore.QRect(10, 160, 281, 41))
        self.comboBox_environment.setObjectName("comboBox_environment")
        self.comboBox_environment.addItem("")
        self.comboBox_environment.setItemText(0, "")
        self.comboBox_environment.addItem("")
        self.comboBox_environment.addItem("")
        self.comboBox_environment.addItem("")
        self.comboBox_environment.addItem("")
        self.comboBox_environment.addItem("")
        self.comboBox_environment.addItem("")
        self.comboBox_environment.addItem("")
        self.comboBox_environment.addItem("")
        self.comboBox_environment.addItem("")
        self.comboBox_environment.addItem("")
        self.comboBox_environment.addItem("")
        self.comboBox_environment.addItem("")
        self.airresistanceframe = QtWidgets.QFrame(self.systemcharacteristics)
        self.airresistanceframe.setGeometry(QtCore.QRect(10, 230, 281, 181))
        self.airresistanceframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.airresistanceframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.airresistanceframe.setObjectName("airresistanceframe")
        self.airresistanceonbut = QtWidgets.QRadioButton(self.airresistanceframe)
        self.airresistanceonbut.setEnabled(True)
        self.airresistanceonbut.setGeometry(QtCore.QRect(10, 10, 21, 41))
        self.airresistanceonbut.setChecked(False)
        self.airresistanceonbut.setObjectName("airresistanceonbut")
        self.airresistanceoffbut = QtWidgets.QRadioButton(self.airresistanceframe)
        self.airresistanceoffbut.setGeometry(QtCore.QRect(10, 70, 21, 41))
        self.airresistanceoffbut.setText("")
        self.airresistanceoffbut.setObjectName("airresistanceoffbut")
        self.label_2 = QtWidgets.QLabel(self.airresistanceframe)
        self.label_2.setGeometry(QtCore.QRect(40, 10, 211, 41))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.airresistanceframe)
        self.label_3.setGeometry(QtCore.QRect(40, 70, 211, 41))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.comparisonbut = QtWidgets.QRadioButton(self.airresistanceframe)
        self.comparisonbut.setGeometry(QtCore.QRect(10, 130, 21, 41))
        self.comparisonbut.setText("")
        self.comparisonbut.setObjectName("comparisonbut")
        self.label_9 = QtWidgets.QLabel(self.airresistanceframe)
        self.label_9.setGeometry(QtCore.QRect(40, 130, 211, 41))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.errorscreen = QtWidgets.QPlainTextEdit(self.tab)
        self.errorscreen.setGeometry(QtCore.QRect(0, 520, 1091, 221))
        self.errorscreen.setObjectName("errorscreen")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(10, 490, 121, 22))
        self.label_4.setObjectName("label_4")
        self.calculate = QtWidgets.QPushButton(self.tab)
        self.calculate.setGeometry(QtCore.QRect(380, 760, 341, 38))
        self.calculate.setObjectName("calculate")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.plot = PlotWidget(self.tab_2)
        self.plot.setGeometry(QtCore.QRect(20, 20, 1051, 781))
        self.plot.setObjectName("plot")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.coords_table1 = QtWidgets.QTableWidget(self.tab_4)
        self.coords_table1.setGeometry(QtCore.QRect(10, 60, 401, 741))
        self.coords_table1.setObjectName("coords_table1")
        self.coords_table1.setColumnCount(3)
        self.coords_table1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.coords_table1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.coords_table1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.coords_table1.setHorizontalHeaderItem(2, item)
        self.coords_table2 = QtWidgets.QTableWidget(self.tab_4)
        self.coords_table2.setGeometry(QtCore.QRect(430, 60, 401, 741))
        self.coords_table2.setObjectName("coords_table2")
        self.coords_table2.setColumnCount(3)
        self.coords_table2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.coords_table2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.coords_table2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.coords_table2.setHorizontalHeaderItem(2, item)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_2.setGeometry(QtCore.QRect(850, 40, 231, 511))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.savecsv = QtWidgets.QPushButton(self.groupBox_2)
        self.savecsv.setGeometry(QtCore.QRect(10, 100, 211, 38))
        self.savecsv.setObjectName("savecsv")
        self.csvfilename = QtWidgets.QLineEdit(self.groupBox_2)
        self.csvfilename.setGeometry(QtCore.QRect(10, 60, 211, 36))
        self.csvfilename.setObjectName("csvfilename")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(10, 30, 211, 22))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.dbfilename = QtWidgets.QLineEdit(self.groupBox_2)
        self.dbfilename.setGeometry(QtCore.QRect(10, 180, 211, 36))
        self.dbfilename.setText("")
        self.dbfilename.setObjectName("dbfilename")
        self.savedb = QtWidgets.QPushButton(self.groupBox_2)
        self.savedb.setGeometry(QtCore.QRect(10, 220, 211, 38))
        self.savedb.setObjectName("savedb")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(10, 150, 211, 22))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.imagefilename = QtWidgets.QLineEdit(self.groupBox_2)
        self.imagefilename.setGeometry(QtCore.QRect(10, 310, 211, 36))
        self.imagefilename.setText("")
        self.imagefilename.setObjectName("imagefilename")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(10, 261, 211, 41))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 350, 211, 91))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pngbut = QtWidgets.QRadioButton(self.groupBox_3)
        self.pngbut.setGeometry(QtCore.QRect(20, 30, 71, 26))
        self.pngbut.setObjectName("pngbut")
        self.bmpbut = QtWidgets.QRadioButton(self.groupBox_3)
        self.bmpbut.setGeometry(QtCore.QRect(20, 60, 71, 26))
        self.bmpbut.setObjectName("bmpbut")
        self.jpgbut = QtWidgets.QRadioButton(self.groupBox_3)
        self.jpgbut.setGeometry(QtCore.QRect(130, 30, 71, 26))
        self.jpgbut.setObjectName("jpgbut")
        self.svgbut = QtWidgets.QRadioButton(self.groupBox_3)
        self.svgbut.setGeometry(QtCore.QRect(130, 60, 71, 26))
        self.svgbut.setObjectName("svgbut")
        self.saveimage = QtWidgets.QPushButton(self.groupBox_2)
        self.saveimage.setGeometry(QtCore.QRect(10, 450, 211, 38))
        self.saveimage.setObjectName("saveimage")
        self.savetextedit = QtWidgets.QPlainTextEdit(self.tab_4)
        self.savetextedit.setGeometry(QtCore.QRect(850, 560, 231, 241))
        self.savetextedit.setReadOnly(True)
        self.savetextedit.setObjectName("savetextedit")
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        self.label_12.setGeometry(QtCore.QRect(10, 21, 401, 41))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_4)
        self.label_13.setGeometry(QtCore.QRect(430, 21, 401, 41))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.environment_table = QtWidgets.QTableWidget(self.tab_3)
        self.environment_table.setGeometry(QtCore.QRect(50, 20, 541, 431))
        self.environment_table.setObjectName("environment_table")
        self.environment_table.setColumnCount(2)
        self.environment_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.environment_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.environment_table.setHorizontalHeaderItem(1, item)
        self.environment_table.horizontalHeader().setDefaultSectionSize(253)
        self.material_table = QtWidgets.QTableWidget(self.tab_3)
        self.material_table.setGeometry(QtCore.QRect(650, 20, 431, 781))
        self.material_table.setObjectName("material_table")
        self.material_table.setColumnCount(2)
        self.material_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.material_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.material_table.setHorizontalHeaderItem(1, item)
        self.material_table.horizontalHeader().setDefaultSectionSize(198)
        self.planet_table = QtWidgets.QTableWidget(self.tab_3)
        self.planet_table.setGeometry(QtCore.QRect(10, 460, 631, 341))
        self.planet_table.setObjectName("planet_table")
        self.planet_table.setColumnCount(2)
        self.planet_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.planet_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.planet_table.setHorizontalHeaderItem(1, item)
        self.planet_table.horizontalHeader().setDefaultSectionSize(298)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.HtmlViewer = QWebView(self.tab_5)
        self.HtmlViewer.setGeometry(QtCore.QRect(0, 0, 1091, 821))
        self.HtmlViewer.setUrl(QtCore.QUrl("about:blank"))
        self.HtmlViewer.setObjectName("HtmlViewer")
        self.tabWidget.addTab(self.tab_5, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Projectile simulation"))
        self.groupBox.setTitle(_translate("MainWindow", "Характеристики Тела"))
        self.comboBox_density.setItemText(1, _translate("MainWindow", "Литий"))
        self.comboBox_density.setItemText(2, _translate("MainWindow", "Натрий"))
        self.comboBox_density.setItemText(3, _translate("MainWindow", "Бериллий"))
        self.comboBox_density.setItemText(4, _translate("MainWindow", "Алюминий"))
        self.comboBox_density.setItemText(5, _translate("MainWindow", "Германий"))
        self.comboBox_density.setItemText(6, _translate("MainWindow", "Хром"))
        self.comboBox_density.setItemText(7, _translate("MainWindow", "Железо"))
        self.comboBox_density.setItemText(8, _translate("MainWindow", "Медь"))
        self.comboBox_density.setItemText(9, _translate("MainWindow", "Серебро"))
        self.comboBox_density.setItemText(10, _translate("MainWindow", "Свинец"))
        self.comboBox_density.setItemText(11, _translate("MainWindow", "Палладий"))
        self.comboBox_density.setItemText(12, _translate("MainWindow", "Уран"))
        self.comboBox_density.setItemText(13, _translate("MainWindow", "Золото"))
        self.comboBox_density.setItemText(14, _translate("MainWindow", "Платина"))
        self.comboBox_density.setItemText(15, _translate("MainWindow", "Иридий"))
        self.density_label.setText(_translate("MainWindow", "Вещество тела"))
        self.speed_label.setText(_translate("MainWindow", "Начальная скорость"))
        self.mass_label.setText(_translate("MainWindow", "Масса тела"))
        self.metresps.setText(_translate("MainWindow", "Метры в секунду"))
        self.kilometresph.setText(_translate("MainWindow", "Километры в час"))
        self.milesph.setText(_translate("MainWindow", "Мили в час"))
        self.yardsps.setText(_translate("MainWindow", "Ярды в секунду"))
        self.kilograms.setText(_translate("MainWindow", "Килограммы"))
        self.pounds.setText(_translate("MainWindow", "Фунты"))
        self.grams.setText(_translate("MainWindow", "Граммы"))
        self.tons.setText(_translate("MainWindow", "Тонны"))
        self.label.setText(_translate("MainWindow", "Начальная высота, метры"))
        self.angle_label.setText(_translate("MainWindow", "Угол между вектором начальной скоростью и осью x"))
        self.degrees.setText(_translate("MainWindow", "Градусы"))
        self.radians.setText(_translate("MainWindow", "Радианы"))
        self.minutes.setText(_translate("MainWindow", "Минуты"))
        self.seconds.setText(_translate("MainWindow", "Секунды"))
        self.systemcharacteristics.setTitle(_translate("MainWindow", "Характеристики Системы"))
        self.planet_label.setText(_translate("MainWindow", "Планета"))
        self.comboBox_planet.setItemText(1, _translate("MainWindow", "Плутон"))
        self.comboBox_planet.setItemText(2, _translate("MainWindow", "Эрида"))
        self.comboBox_planet.setItemText(3, _translate("MainWindow", "Луна"))
        self.comboBox_planet.setItemText(4, _translate("MainWindow", "Меркурий"))
        self.comboBox_planet.setItemText(5, _translate("MainWindow", "Марс"))
        self.comboBox_planet.setItemText(6, _translate("MainWindow", "Уран"))
        self.comboBox_planet.setItemText(7, _translate("MainWindow", "Венера"))
        self.comboBox_planet.setItemText(8, _translate("MainWindow", "Земля"))
        self.comboBox_planet.setItemText(9, _translate("MainWindow", "Сатурн"))
        self.comboBox_planet.setItemText(10, _translate("MainWindow", "Нептун"))
        self.comboBox_planet.setItemText(11, _translate("MainWindow", "Юпитер"))
        self.environment_label.setText(_translate("MainWindow", "Воздушная среда"))
        self.comboBox_environment.setItemText(1, _translate("MainWindow", "Водород"))
        self.comboBox_environment.setItemText(2, _translate("MainWindow", "Гелий"))
        self.comboBox_environment.setItemText(3, _translate("MainWindow", "Метан"))
        self.comboBox_environment.setItemText(4, _translate("MainWindow", "Аммиак"))
        self.comboBox_environment.setItemText(5, _translate("MainWindow", "Воздух"))
        self.comboBox_environment.setItemText(6, _translate("MainWindow", "Аргон"))
        self.comboBox_environment.setItemText(7, _translate("MainWindow", "Углекислый газ"))
        self.comboBox_environment.setItemText(8, _translate("MainWindow", "Хлор"))
        self.comboBox_environment.setItemText(9, _translate("MainWindow", "Криптон"))
        self.comboBox_environment.setItemText(10, _translate("MainWindow", "Ксенон"))
        self.comboBox_environment.setItemText(11, _translate("MainWindow", "Радон"))
        self.comboBox_environment.setItemText(12, _translate("MainWindow", "Гексафторид вольфрама"))
        self.label_2.setText(_translate("MainWindow", "Сопротивление воздуха присутсвует"))
        self.label_3.setText(_translate("MainWindow", "Сопротивление воздуха Отсутсвует"))
        self.label_9.setText(_translate("MainWindow", "Сравнение(оба случая на одном графике)"))
        self.label_4.setText(_translate("MainWindow", "Вывод ошибок"))
        self.calculate.setText(_translate("MainWindow", "Рассчитать траекторию и построить график"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Условия симуляции"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2),
                                  _translate("MainWindow", "Симуляция в виде графика"))
        item = self.coords_table1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Время t, с"))
        item = self.coords_table1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "X, м"))
        item = self.coords_table1.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Y, м"))
        item = self.coords_table2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Время t, с"))
        item = self.coords_table2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "X, м"))
        item = self.coords_table2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Y, м"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Сохранить таблицу"))
        self.savecsv.setText(_translate("MainWindow", "Сохранить в формате .csv"))
        self.label_10.setText(_translate("MainWindow", "Название файла без.csv"))
        self.savedb.setText(_translate("MainWindow", "Сохранить в формате .db"))
        self.label_11.setText(_translate("MainWindow", "Название файла без.db"))
        self.label_14.setText(_translate("MainWindow", "Название файла без расширения"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Форматы"))
        self.pngbut.setText(_translate("MainWindow", "PNG"))
        self.bmpbut.setText(_translate("MainWindow", "BMP"))
        self.jpgbut.setText(_translate("MainWindow", "JPG"))
        self.svgbut.setText(_translate("MainWindow", "SVG"))
        self.saveimage.setText(_translate("MainWindow", "Сохранить изображение"))
        self.label_12.setText(_translate("MainWindow", "Без сопротивления воздуха"))
        self.label_13.setText(_translate("MainWindow", "С сопротивлением воздуха"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Таблица координат"))
        item = self.environment_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Воздушная среда"))
        item = self.environment_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Плотность"))
        item = self.material_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Вещество"))
        item = self.material_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Плотность"))
        item = self.planet_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Планета"))
        item = self.planet_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Ускорение свободного падения"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3),
                                  _translate("MainWindow", "Таблица физических величин"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5),
                                  _translate("MainWindow", "Теоритетические материалы"))


class ConfirmationWindow(QtWidgets.QWidget):
    data = QtCore.pyqtSignal(bool, str)

    def __init__(self):
        super(ConfirmationWindow, self).__init__()
        self.fname = ""
        self.setWindowTitle("Подтверждение")
        self.setFixedHeight(150)
        self.setFixedWidth(400)
        self.setWindowModality(QtCore.Qt.ApplicationModal)
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(40, 20, 315, 22)
        self.label.setText("Вы хотите изменить существующий файл?")
        self.Ybutton = QtWidgets.QPushButton(self)
        self.Ybutton.setGeometry(50, 80, 100, 40)
        self.Ybutton.setText("Да")
        self.Nbutton = QtWidgets.QPushButton(self)
        self.Nbutton.setGeometry(250, 80, 100, 40)
        self.Nbutton.setText("Нет")

        self.Ybutton.clicked.connect(self.yes)
        self.Nbutton.clicked.connect(self.no)

    def no(self):
        self.data.emit(False, self.fname)
        self.close()

    def yes(self):
        self.data.emit(True, self.fname)
        self.close()
